name: CI_IBM

on: [push]

jobs: 
  build:
    runs-on: ubuntu-20.04
    steps: 
    - name: Roda um script shell
      run: echo "olá git actions"

  test:
    runs-on: ubuntu-20.04
    steps: 
    - name: Roda um script shell
      run: echo "olá git actions rodando test"